# Generated by Django 5.2.17 on 2026-10-01 22:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, unique=True)),
                ('kind', models.CharField(choices=[('embassy', 'Ambasada'), ('consulate', 'Konzulat'), ('honorary', 'Počasni konzulat'), ('international', 'Međunarodna organizacija')], max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True, max_length=1000)),
                ('evidence_url', models.URLField(blank=True, max_length=1000)),
                ('verified_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('adapter', models.CharField(choices=[('none', 'Bez adaptera'), ('eeas', 'EEAS'), ('govuk', 'GOV.UK'), ('generic', 'Strukturirana lista')], default='none', max_length=20)),
                ('adapter_config', models.JSONField(blank=True, default=dict, help_text='Optional listing URL patterns and link selectors')),
                ('status', models.CharField(choices=[('discovered', 'Otkriven'), ('verified', 'Provjeren'), ('unsupported', 'Čeka integraciju'), ('blocked', 'Nedostupan'), ('none', 'Izvor nije pronađen'), ('failing', 'Greška')], default='discovered', max_length=20)),
                ('enabled', models.BooleanField(default=False)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='board.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('candidates', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='board.source')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=250)),
                ('canonical_url', models.URLField(max_length=1000)),
                ('application_url', models.URLField(blank=True, max_length=1000)),
                ('title', models.CharField(max_length=400)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('opportunity_type', models.CharField(choices=[('employment', 'Zaposlenje'), ('paid_internship', 'Plaćena praksa'), ('consultancy', 'Individualni konsultantski angažman')], default='employment', max_length=30)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('open_until_filled', models.BooleanField(default=False)),
                ('location_evidence', models.TextField(blank=True)),
                ('eligibility', models.TextField(blank=True)),
                ('source_published_at', models.DateField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('missing_scans', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('review', 'Na provjeri'), ('published', 'Objavljeno'), ('closed', 'Zatvoreno')], default='review', max_length=20)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('raw_text', models.TextField(blank=True)),
                ('manually_edited_fields', models.JSONField(blank=True, default=list)),
                ('field_evidence', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='board.source')),
            ],
        ),
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_hash', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='board.source')),
            ],
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(fields=('organization', 'url'), name='unique_org_source'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'first_seen_at'], name='board_job_status_b7a348_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['deadline'], name='board_job_deadlin_5136fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('source', 'canonical_url'), name='unique_source_job_url'),
        ),
        migrations.AddIndex(
            model_name='sourcedocument',
            index=models.Index(fields=['fetched_at'], name='board_sourc_fetched_fe2750_idx'),
        ),
    ]
