# Generated by Django 5.2.17 on 2026-10-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='adapter',
            field=models.CharField(choices=[('none', 'Bez adaptera'), ('eeas', 'EEAS'), ('govuk', 'GOV.UK'), ('generic', 'Strukturirana lista'), ('denmark', 'Ambasada Danske'), ('italy', 'Ambasada Italije'), ('swiss', 'Ambasada Švicarske')], default='none', max_length=20),
        ),
    ]
