# Generated by Django 5.2.17 on 2026-10-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_source_adapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='adapter',
            field=models.CharField(choices=[('none', 'Bez adaptera'), ('eeas', 'EEAS'), ('govuk', 'GOV.UK'), ('generic', 'Strukturirana lista'), ('denmark', 'Ambasada Danske'), ('italy', 'Ambasada Italije'), ('swiss', 'Ambasada Švicarske'), ('osce', 'Misija OSCE-a'), ('unct', 'UN u BiH'), ('ohr', 'OHR'), ('eufor', 'EUFOR'), ('unicef', 'UNICEF'), ('ebrd', 'EBRD'), ('rcc', 'RCC')], default='none', max_length=20),
        ),
    ]
