# Generated by Django 5.2.17 on 2026-10-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_alter_source_adapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='closed_reason',
            field=models.CharField(blank=True, choices=[('deadline', 'Istekao rok'), ('missing', 'Nestao sa izvora'), ('stale', 'Bez roka, zastario'), ('manual', 'Zatvoren ručno')], max_length=20),
        ),
    ]
