# Generated by Django 5.2.17 on 2026-10-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_job_closed_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='scope',
            field=models.CharField(blank=True, choices=[('national', 'Nacionalna pozicija'), ('international', 'Međunarodna pozicija')], max_length=20),
        ),
    ]
