# Generated by Django 5.2.17 on 2026-10-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_alter_source_adapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='closed_reason',
            field=models.CharField(blank=True, choices=[('deadline', 'Istekao rok'), ('missing', 'Nestao sa izvora'), ('stale', 'Bez roka, zastario'), ('withdrawn', 'Povučen na izvoru'), ('manual', 'Zatvoren ručno')], max_length=20),
        ),
    ]
