# Generated by Django 5.2.17 on 2026-10-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0019_source_adapter_rai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='adapter',
            field=models.CharField(choices=[('none', 'Bez adaptera'), ('eeas', 'EEAS'), ('govuk', 'GOV.UK'), ('generic', 'Strukturirana lista'), ('denmark', 'Ambasada Danske'), ('italy', 'Ambasada Italije'), ('swiss', 'Ambasada Švicarske'), ('osce', 'Misija OSCE-a'), ('unct', 'UN u BiH'), ('ohr', 'OHR'), ('eufor', 'EUFOR'), ('unicef', 'UNICEF'), ('ebrd', 'EBRD'), ('rcc', 'RCC'), ('era', 'Ambasada SAD (ERA)'), ('japan', 'Ambasada Japana'), ('oracle', 'Oracle Recruiting (UN agencije)'), ('workday', 'Workday (UNHCR)'), ('coe', 'Vijeće Evrope'), ('uncareers', 'UN Sekretarijat (careers.un.org)'), ('csod', 'Cornerstone (Svjetska banka)'), ('taleo', 'Taleo (WHO)'), ('bamboohr', 'BambooHR (ICMP)'), ('rmk', 'SuccessFactors (UNESCO)'), ('rai', 'RAI'), ('taleoftl', 'Taleo, stariji (NATO)')], default='none', max_length=20),
        ),
    ]
