# Generated by Django 5.2.17 on 2026-10-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0022_source_adapter_lanteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='recruitment_checked_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='recruitment_evidence_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='organization',
            name='recruitment_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='recruitment_status',
            field=models.CharField(blank=True, choices=[('', 'Nije provjeren'), ('not_found', 'Izvor nije pronađen'), ('integration', 'Čeka integraciju'), ('blocked', 'Provjera nije uspjela')], max_length=20),
        ),
    ]
