# Generated by Django 5.2.17 on 2026-10-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0023_organization_recruitment_checked_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sourcedocument',
            index=models.Index(fields=['source', 'url', '-fetched_at'], name='sourcedoc_latest'),
        ),
    ]
