# Generated by Django 5.2.17 on 2026-10-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0026_alter_organization_kind_alter_source_adapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='kind',
            field=models.CharField(choices=[('aggregator', 'Agregator poslova'), ('embassy', 'Ambasada'), ('consulate', 'Konzulat'), ('honorary', 'Počasni konzulat'), ('international', 'Međunarodna organizacija'), ('ngo', 'Međunarodna nevladina organizacija')], max_length=20),
        ),
    ]
