# Generated by Django 5.2.17 on 2026-10-03 09:26

from django.db import migrations, models


def rename_coe(apps, schema_editor, old="coe", new="avature"):
    apps.get_model("board", "Source").objects.filter(adapter=old).update(adapter=new)


def restore_coe(apps, schema_editor):
    rename_coe(apps, schema_editor, "avature", "coe")


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0027_organization_kind_ngo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='adapter',
            field=models.CharField(choices=[('none', 'Bez adaptera'), ('eeas', 'EEAS'), ('govuk', 'GOV.UK'), ('generic', 'Strukturirana lista'), ('denmark', 'Ambasada Danske'), ('italy', 'Ambasada Italije'), ('swiss', 'Ambasada Švicarske'), ('osce', 'Misija OSCE-a'), ('unct', 'UN u BiH'), ('ohr', 'OHR'), ('eufor', 'EUFOR'), ('unicef', 'UNICEF'), ('ebrd', 'EBRD'), ('rcc', 'RCC'), ('era', 'Ambasada SAD (ERA)'), ('japan', 'Ambasada Japana'), ('oracle', 'Oracle Recruiting (UN agencije)'), ('workday', 'Workday (UNHCR)'), ('avature', 'Avature (Vijeće Evrope, UNOPS)'), ('uncareers', 'UN Sekretarijat (careers.un.org)'), ('csod', 'Cornerstone (Svjetska banka)'), ('taleo', 'Taleo (WHO)'), ('bamboohr', 'BambooHR (ICMP)'), ('rmk', 'SuccessFactors (UNESCO)'), ('rai', 'RAI'), ('taleoftl', 'Taleo, stariji (NATO)'), ('sfrss', 'SuccessFactors RSS (ILO)'), ('lanteria', 'Lanteria (ICMPD)'), ('turkey', 'Turske lokalne objave'), ('spain', 'Ambasada Spanije'), ('brazil', 'Ambasada Brazila'), ('slovenia', 'Slovenija MZEZ'), ('canadales', 'Kanada LES'), ('peoplesoft', 'PeopleSoft Atom feed (EIB)'), ('sitemap', 'Sitemap misije (Njemačka)'), ('reliefweb', 'ReliefWeb'), ('impactpool', 'Impactpool')], default='none', max_length=20),
        ),
        migrations.RunPython(rename_coe, restore_coe),
    ]
