# Generated by Django 5.2.17 on 2026-10-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0028_source_adapter_avature_peoplesoft_sitemap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='kind',
            field=models.CharField(choices=[('aggregator', 'Agregator poslova'), ('embassy', 'Ambasada'), ('consulate', 'Konzulat'), ('honorary', 'Počasni konzulat'), ('international', 'Međunarodna organizacija'), ('ngo', 'Međunarodna nevladina organizacija'), ('agency', 'Razvojna agencija')], max_length=20),
        ),
        migrations.AlterField(
            model_name='source',
            name='adapter',
            field=models.CharField(choices=[('none', 'Bez adaptera'), ('eeas', 'EEAS'), ('govuk', 'GOV.UK'), ('generic', 'Strukturirana lista'), ('denmark', 'Ambasada Danske'), ('italy', 'Ambasada Italije'), ('swiss', 'Ambasada Švicarske'), ('osce', 'Misija OSCE-a'), ('unct', 'UN u BiH'), ('ohr', 'OHR'), ('eufor', 'EUFOR'), ('unicef', 'UNICEF'), ('ebrd', 'EBRD'), ('rcc', 'RCC'), ('era', 'Ambasada SAD (ERA)'), ('japan', 'Ambasada Japana'), ('oracle', 'Oracle Recruiting (UN agencije)'), ('workday', 'Workday (UNHCR)'), ('avature', 'Avature (Vijeće Evrope, UNOPS)'), ('uncareers', 'UN Sekretarijat (careers.un.org)'), ('csod', 'Cornerstone (Svjetska banka)'), ('taleo', 'Taleo (WHO)'), ('bamboohr', 'BambooHR (ICMP)'), ('rmk', 'SuccessFactors (UNESCO)'), ('rai', 'RAI'), ('taleoftl', 'Taleo, stariji (NATO)'), ('sfrss', 'SuccessFactors RSS (ILO)'), ('lanteria', 'Lanteria (ICMPD)'), ('turkey', 'Turske lokalne objave'), ('spain', 'Ambasada Spanije'), ('brazil', 'Ambasada Brazila'), ('slovenia', 'Slovenija MZEZ'), ('canadales', 'Kanada LES'), ('peoplesoft', 'PeopleSoft Atom feed (EIB)'), ('sitemap', 'Sitemap misije (Njemačka)'), ('wordpress', 'WordPress oglasnik (mreza-mira.net)'), ('reliefweb', 'ReliefWeb'), ('impactpool', 'Impactpool')], default='none', max_length=20),
        ),
    ]
