# Generated by Django 5.2.17 on 2026-10-03 10:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0031_source_adapter_kemlu'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='education_level',
            field=models.CharField(blank=True, choices=[('secondary', 'Srednja škola'), ('bachelor', 'Fakultet (bachelor)'), ('master', 'Master'), ('phd', 'Doktorat')], max_length=20, verbose_name='minimalno obrazovanje'),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='godine iskustva'),
        ),
        migrations.AddField(
            model_name='job',
            name='fields_of_study',
            field=models.JSONField(blank=True, default=list, verbose_name='oblasti studija'),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('expired', 'Oglas je istekao ili je mjesto popunjeno'), ('wrong_info', 'Netačni podaci (rok, lokacija, uslovi)'), ('broken_link', 'Link ne radi'), ('not_bih', 'Posao nije u Bosni i Hercegovini'), ('duplicate', 'Oglas je duplikat'), ('suspicious', 'Sumnjiv ili lažan oglas'), ('missing', 'Nedostaje oglas ili poslodavac'), ('site', 'Greška na stranici'), ('other', 'Drugo')], max_length=20, verbose_name='razlog')),
                ('message', models.TextField(blank=True, max_length=2000, verbose_name='poruka')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail za odgovor')),
                ('page_url', models.CharField(blank=True, max_length=500, verbose_name='stranica')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('new', 'Novo'), ('resolved', 'Riješeno'), ('dismissed', 'Odbačeno')], default='new', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, verbose_name='bilješka')),
                ('client_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='board.job')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='board_repor_status_461532_idx')],
            },
        ),
    ]
