# Generated by Django 5.2.17 on 2026-10-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0032_job_requirements_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
