# Generated by Django 5.2.17 on 2026-10-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0035_job_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='closed_reason',
            field=models.CharField(blank=True, choices=[('deadline', 'Istekao rok'), ('missing', 'Nestao sa izvora'), ('stale', 'Bez roka, zastario'), ('withdrawn', 'Povučen na izvoru'), ('manual', 'Zatvoren ručno'), ('archive', 'Preuzet iz arhive izvora')], max_length=20),
        ),
    ]
