# Generated by Django 5.2.17 on 2026-10-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0037_job_closed_reason_duplicate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='education_level',
            field=models.CharField(blank=True, choices=[('secondary', 'Srednja škola'), ('junior_college', 'Viša škola'), ('bachelor', 'Fakultet (bachelor)'), ('master', 'Master'), ('phd', 'Doktorat')], max_length=20, verbose_name='minimalno obrazovanje'),
        ),
    ]
