# Generated by Django 5.2.18 on 2026-10-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0038_job_education_junior_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='name_en',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
